export const GET_WEATHER_BY_CITY_ID = 'GET_WEATHER_BY_CITY_ID';
export const GET_WEATHER_BY_CITY_ID_SUCCESS = 'GET_WEATHER_BY_CITY_ID_SUCCESS';
export const GET_WEATHER_BY_ZIP_CODE = 'GET_WEATHER_BY_ZIP_CODE';
export const GET_WEATHER_BY_ZIP_CODE_SUCCESS = 'GET_WEATHER_BY_ZIP_CODE_SUCCESS';
export const SET_UNIT = 'SET_UNIT';
export const SET_UNIT_SUCCESS = 'SET_UNIT_SUCCESS';